#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-GenderFromName
version:      0.32
version_from: GenderFromName.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
